# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-25 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_buyproduct_user_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineproduct', to='phoneShop.Product'),
        ),
    ]
